-- Canonical enum types enforced at application layer via @Enumerated(STRING).
-- No DDL changes required: existing VARCHAR columns store enum names (e.g. 'MEDICO', 'CARDIOLOGIA').
-- Seed data is re-generated by DatabaseSeeder.run() on startup (dev/test profiles).
SELECT 1;
